- hosts: all
  become: yes
  tags: [setup]
  environment:
    LC_ALL: en_US.utf8
    LANG: en_US.utf8
  tasks:
    - apt: update_cache=yes
    - apt: name=aptitude state=latest
    - apt: upgrade=safe

    # Install basic requirements
    - apt: name={{item}} state=latest
      with_items:
        - fluxbox
        - xorg
        - unzip
        - vim
        - default-jre

    # Install firefox
    - apt: name=firefox state=latest

    # Install chrome
    - get_url: url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" dest=/tmp/google-chrome-stable_current_amd64.deb mode=0644
    - shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb
      failed_when: false
    - shell: apt-get --yes --fix-broken install warn=false

    # Install chromedriver
    - shell: curl "http://chromedriver.storage.googleapis.com/LATEST_RELEASE" warn=false
      register: chromedriver_version
    - unarchive: src="http://chromedriver.storage.googleapis.com/{{chromedriver_version.stdout}}/chromedriver_linux64.zip" dest=/usr/local/bin mode=0755 copy=no
    - file: path=/home/vagrant/chromedriver state=directory mode=0755
    - copy: src=files/selenium/chromedriver.service dest=/etc/systemd/system/chromedriver.service owner=root group=root mode=0644
    - service: name=chromedriver enabled=yes

    # Install Xvfb
    - apt: name=xvfb state=latest
    - copy: src=files/selenium/xvfb.service dest=/etc/systemd/system/xvfb.service owner=root group=root mode=0644
    - service: name=xvfb enabled=yes

    # Install x11vnc
    - apt: name=x11vnc state=latest
    - copy: src=files/selenium/x11vnc.service dest=/etc/systemd/system/x11vnc.service owner=root group=root mode=0644
    - service: name=x11vnc enabled=yes

    # Install selenium
    - shell: curl "https://selenium-release.storage.googleapis.com/" | perl -n -e'/.*<Key>([^>]+selenium-server-standalone[^<]+)/ && print $1' warn=false
      register: selenium_version
    - get_url: url="https://selenium-release.storage.googleapis.com/{{selenium_version.stdout}}" dest=/usr/local/bin/selenium-server-standalone.jar
    - file: path=/home/vagrant/selenium state=directory mode=0755
    - copy: src=files/selenium/selenium.service dest=/etc/systemd/system/selenium.service owner=root group=root mode=0644
    - service: name=selenium enabled=yes

    - shell: systemctl daemon-reload
    - service: name=xvfb state=restarted
    - service: name=x11vnc state=restarted
    - service: name=chromedriver state=restarted
    - service: name=selenium state=restarted
