services:
   - "postgres:9.4"
   - "selenium/standalone-firefox:latest"
   - "selenium/standalone-chrome:latest"

before_script:
    - export SYMFONY_ENV=test
    - export CONFIG_DATABASE_URL=psql://postgres@postgres/app
    - export SELENIUM_FIREFOX_HOST=selenium__standalone-firefox
    - export SELENIUM_CHROME_HOST=selenium__standalone-chrome
    - psql -h postgres -U postgres -q -c 'create database app;'
    - bin/fill_parameters
    - composer install --no-interaction --optimize-autoloader
    - npm config set cache /cache/npm
    - npm install
    - bin/symfony doctrine:schema:create --no-interaction
    - cp -f test/data/nginx_default.conf /etc/nginx/sites-available/default
    - sed -e "s?%CI_PROJECT_DIR%?$(pwd)?g" --in-place /etc/nginx/sites-available/default
    - service php5-fpm start
    - service nginx start

kahlan:
    script:
        - export MINK_DEFAULT_BROWSER=firefox
        - bin/kahlan
