language: php

php:
    - 5.5
    # - 5.6
    # - hhvm

before_script:
    - composer install --prefer-source --no-interaction
    - npm install
    - npm install -g bower
    - npm install -g gulp
    - bower install
    - gulp build

# Note for phpspec: Using awk to strip the output line from the coverage generator
script:
    - bin/phpspec run --ansi --format=junit --no-code-generation --no-interaction | awk 'NR>1{print buf}{buf = $0}' > phpspec.xml
    - gulp symfony & PNUM=$! && sleep 5 && bin/behat --ansi --no-snippets --strict --format=junit --out=behat.xml && kill $PNUM
