version: '2'
services:
    app:
        build:
            context: .
            args:
                USER_ID: $USER_ID
        depends_on:
            - psql
            - mailhog
            - selenium
            - chrome
            - firefox
        volumes:
            - ".:/app"
            - "./tasks/files/php.ini:/etc/php5/cli/php.ini"
            - "./tasks/files/php.ini:/etc/php5/fpm/php.ini"
            - "./tasks/files/php-fpm.conf:/etc/php5/fpm/php-fpm.conf"
        command: /usr/sbin/php5-fpm
        environment:
            USE_POLLING_WATCHES: 1
            VAGRANT: 1
            PGHOST: psql

    psql:
        image: postgres:9.4
        environment:
            POSTGRES_USER: tg
        ports:
            - "5432:5432"

    mailhog:
        image: mailhog/mailhog:latest
        environment:
            MH_API_BIND_ADDR: 0.0.0.0:1080
            MH_UI_BIND_ADDR: 0.0.0.0:1080
            MH_SMTP_BIND_ADDR: 0.0.0.0:1025
        ports:
            - "1080:1080"

    nginx:
        image: nginx:latest
        depends_on:
            - app
        volumes:
            - ".:/app"
            - "./tasks/files/nginx.dev.conf:/etc/nginx/conf.d/dev.conf"
            - "./tasks/files/nginx.prod.conf:/etc/nginx/conf.d/prod.conf"
        ports:
            - "80:80"
            - "8080:8080"

    selenium:
        image: selenium/hub
        ports:
            - "4444:4444"

    chrome:
        image: selenium/node-chrome-debug
        # See: https://github.com/SeleniumHQ/docker-selenium/issues/91
        command: bash -c "sed -e '19a\echo no_proxy >> asseluser' /opt/bin/entry_point.sh | bash"
        environment:
             HUB_PORT_4444_TCP_ADDR: selenium
        depends_on:
            - selenium
        ports:
            - "15900:5900"

    firefox:
        image: selenium/node-firefox-debug
        # See: https://github.com/SeleniumHQ/docker-selenium/issues/91
        command: bash -c "sed -e '19a\echo no_proxy >> asseluser' /opt/bin/entry_point.sh | bash"
        environment:
            HUB_PORT_4444_TCP_ADDR: selenium
        depends_on:
            - selenium
        ports:
            - "15901:5900"
