okoa:
    resource: "@OkoaBundle/Controller/"
    type:     annotation
    prefix:   /okoa

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
